// festiflux/assets/vue/controllers/ListesPostes.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { Backend } from "../../scripts/Backend";
import PosteForm from "./PosteForm.vue";
import { Poste } from "../../scripts/types";

interface Props {
  festivalId: number;
  festivalName: string;
}

const props = defineProps<Props>();

const defaultPoste = {
  id: null,
  nom: "",
  couleur: "#347deb",
  description: "",
};

const posteOpened = ref(false);
const currentPoste = ref<Poste>(defaultPoste);
const posteList = ref<Poste[]>([]);
const askingForDelete = ref(false);

const setAskingForDelete = (value: boolean) => {
  askingForDelete.value = value;
};

const setPosteOpened = (value: boolean) => {
  posteOpened.value = value;
};

const setCurrentPoste = (value: Poste) => {
  currentPoste.value = value;
};

const updateCurrentPoste = (f: (p: Poste) => void) => {
  f(currentPoste.value);
};

const setPosteList = (value: Poste[]) => {
  posteList.value = value;
};

const openPoste = (poste: Poste) => {
  if (askingForDelete.value) return;

  currentPoste.value = poste;

  posteOpened.value = true;
};

const newPoste = () => {
  if (askingForDelete.value) return;
  currentPoste.value = defaultPoste;
  posteOpened.value = true;
};

onMounted(async () => {
  const listeOfPostes = await Backend.getPostes(props.festivalId);
  posteList.value = listeOfPostes;
});
</script>

<template>
  <h2 class="poste-section" :class="{ blurred: askingForDelete }">
    {{ festivalName }}
  </h2>

  <div class="poste-list-wrapper">
    <div class="poste-list" :class="{ blurred: askingForDelete }">
      <h3>Liste des postes</h3>
      <div class="postes">
        <div
          v-for="poste in posteList"
          :style="{
            'border-color': poste.couleur,
            'background-color': poste.couleur + '1A',
          }"
          class="poste pointer"
          @click="(e) => openPoste(poste)"
        >
          {{ poste.nom }}
        </div>
      </div>

      <div v-if="!posteOpened" class="new-poste-btn pointer">
        Ajouter un poste
      </div>
    </div>

    <PosteForm
        v-if="posteOpened"
        :festivalId="props.festivalId"
        :askingForDelete="askingForDelete"
        :setAskingForDelete="setAskingForDelete"
        :posteOpened="posteOpened"
        :setPosteOpened="setPosteOpened"
        :currentPoste="currentPoste"
        :setCurrentPoste="setCurrentPoste"
        :updateCurrentPoste="updateCurrentPoste"
        :posteList="posteList"
        :setPosteList="setPosteList"
    />
  </div>
</template>

// festiflux/assets/svelte/controllers/ListesPostes.svelte
<script>
    import { onMount } from 'svelte';
    import { fade, fly } from 'svelte/transition';
    import { Backend } from '../../scripts/Backend.ts'
    import { posteOpened, currentPoste, posteList, askingForDelete } from '../stores/posteStores.js'
    import PosteForm from './PosteForm.svelte';

    export let festivalId;
    export let festivalName;

    const openPoste = (poste) => {
        if ($askingForDelete) return;

        currentPoste.update((value) => {
            value.id = poste.id;
            value.name = poste.nom;
            value.color = poste.couleur;
            value.desc = poste.description;
            return value;
        });

        posteOpened.set(true);
    }

    const newPoste = () => {
        if ($askingForDelete) return;
        currentPoste.set({
            id: null,
            name: '',
            color: '#347deb',
            desc: '',
        });
        posteOpened.set(true);
    }

    onMount(async () => {
        const listeOfPostes = await Backend.getPostes(parseInt(festivalId));
        posteList.set(listeOfPostes);
    });
</script>

<h2 class="poste-section" class:blurred={$askingForDelete}>{ festivalName }</h2>

<div class="poste-list-wrapper">
    <div class="poste-list" class:blurred={$askingForDelete} transition:fly>
        <h3>Liste des postes</h3>
        <div class="postes">
            {#each $posteList as poste}
                <div 
                    style:border-color={poste.couleur}
                    style:background-color={poste.couleur + '1A'}
                    class="poste pointer" transition:fade 
                    on:click={() => openPoste(poste)}
                >{poste.nom}</div>
            {/each}
        </div>

        {#if !$posteOpened}
            <div class="new-poste-btn pointer" transition:fade on:click={newPoste} style:font-weight="500">Ajouter un poste</div>
        {/if}
    </div>

    {#if $posteOpened}
        <PosteForm {festivalId} />
    {/if}
</div>

<style>
    * {
        transition: filter 0.2s;
    }
</style>
